In [107]:
import pandas as pd
import numpy as np

In [108]:
data=pd.read_excel("/Users/krishuppal/Desktop/data.xlsx")

In [109]:
data

Fund Name    P1    P2   P3    P4     P5
0        M1  0.84  0.71  6.7  42.1  12.59
1        M2  0.91  0.83  7.0  31.7  10.11
2        M3  0.79  0.62  4.8  46.7  13.23
3        M4  0.78  0.61  6.4  42.4  12.55
4        M5  0.94  0.88  3.6  62.2  16.91
5        M6  0.88  0.77  6.5  51.5  14.91
6        M7  0.66  0.44  5.3  48.9  13.83
7        M8  0.93  0.86  3.4  37.0  10.55

In [110]:
data=np.array(data)
data2=data
data2

array([['M1', 0.84, 0.71, 6.7, 42.1, 12.59],
       ['M2', 0.91, 0.83, 7.0, 31.7, 10.11],
       ['M3', 0.79, 0.62, 4.8, 46.7, 13.23],
       ['M4', 0.78, 0.61, 6.4, 42.4, 12.55],
       ['M5', 0.94, 0.88, 3.6, 62.2, 16.91],
       ['M6', 0.88, 0.77, 6.5, 51.5, 14.91],
       ['M7', 0.66, 0.44, 5.3, 48.9, 13.83],
       ['M8', 0.93, 0.86, 3.4, 37.0, 10.55]], dtype=object)

In [111]:
column_index = 1
column_data = data[:, column_index]
column_norm = np.linalg.norm(column_data)
normalized_column = column_data / column_norm
data[:, column_index] = normalized_column
print("Normalized data:", data)

Normalized data: [['M1' 0.3510774374599885 0.71 6.7 42.1 12.59]
 ['M2' 0.3803338905816542 0.83 7.0 31.7 10.11]
 ['M3' 0.33017997094451296 0.62 4.8 46.7 13.23]
 ['M4' 0.3260004776414179 0.61 6.4 42.4 12.55]
 ['M5' 0.3928723704909395 0.88 3.6 62.2 16.91]
 ['M6' 0.36779541067236887 0.77 6.5 51.5 14.91]
 ['M7' 0.27584655800427665 0.44 5.3 48.9 13.83]
 ['M8' 0.3886928771878444 0.86 3.4 37.0 10.55]]


In [112]:
column_index = 2
column_data = data[:, column_index]
column_norm = np.linalg.norm(column_data)
normalized_column = column_data / column_norm
data[:, column_index] = normalized_column
print("Normalized data:", data)

Normalized data: [['M1' 0.3510774374599885 0.3444005875515928 6.7 42.1 12.59]
 ['M2' 0.3803338905816542 0.4026091375603127 7.0 31.7 10.11]
 ['M3' 0.33017997094451296 0.3007441750450529 4.8 46.7 13.23]
 ['M4' 0.3260004776414179 0.2958934625443262 6.4 42.4 12.55]
 ['M5' 0.3928723704909395 0.42686270006394605 3.6 62.2 16.91]
 ['M6' 0.36779541067236887 0.3735048625559528 6.5 51.5 14.91]
 ['M7' 0.27584655800427665 0.21343135003197303 5.3 48.9 13.83]
 ['M8' 0.3886928771878444 0.41716127506249273 3.4 37.0 10.55]]


In [113]:
column_index = 3
column_data = data[:, column_index]
column_norm = np.linalg.norm(column_data)
normalized_column = column_data / column_norm
data[:, column_index] = normalized_column
print("Normalized data:", data)

Normalized data: [['M1' 0.3510774374599885 0.3444005875515928 0.4214336606940341 42.1
  12.59]
 ['M2' 0.3803338905816542 0.4026091375603127 0.4403038246057073 31.7
  10.11]
 ['M3' 0.33017997094451296 0.3007441750450529 0.30192262258677066 46.7
  13.23]
 ['M4' 0.3260004776414179 0.2958934625443262 0.402563496782361 42.4 12.55]
 ['M5' 0.3928723704909395 0.42686270006394605 0.22644196694007804 62.2
  16.91]
 ['M6' 0.36779541067236887 0.3735048625559528 0.40885355141958535 51.5
  14.91]
 ['M7' 0.27584655800427665 0.21343135003197303 0.33337289577289264 48.9
  13.83]
 ['M8' 0.3886928771878444 0.41716127506249273 0.21386185766562923 37.0
  10.55]]


In [114]:
column_index = 4
column_data = data[:, column_index]
column_norm = np.linalg.norm(column_data)
normalized_column = column_data / column_norm
data[:, column_index] = normalized_column
print("Normalized data:", data)

Normalized data: [['M1' 0.3510774374599885 0.3444005875515928 0.4214336606940341
  0.3225390836415167 12.59]
 ['M2' 0.3803338905816542 0.4026091375603127 0.4403038246057073
  0.2428619703428997 10.11]
 ['M3' 0.33017997094451296 0.3007441750450529 0.30192262258677066
  0.35778088375436645 13.23]
 ['M4' 0.3260004776414179 0.2958934625443262 0.402563496782361
  0.324837461909746 12.55]
 ['M5' 0.3928723704909395 0.42686270006394605 0.22644196694007804
  0.4765304276128821 16.91]
 ['M6' 0.36779541067236887 0.3735048625559528 0.40885355141958535
  0.3945549360460358 14.91]
 ['M7' 0.27584655800427665 0.21343135003197303 0.33337289577289264
  0.3746356577213816 13.83]
 ['M8' 0.3886928771878444 0.41716127506249273 0.21386185766562923
  0.28346665308161795 10.55]]


In [115]:
column_index = 5
column_data = data[:, column_index]
column_norm = np.linalg.norm(column_data)
normalized_column = column_data / column_norm
data[:, column_index] = normalized_column
print("Normalized data:", data)

Normalized data: [['M1' 0.3510774374599885 0.3444005875515928 0.4214336606940341
  0.3225390836415167 0.3359922875547845]
 ['M2' 0.3803338905816542 0.4026091375603127 0.4403038246057073
  0.2428619703428997 0.2698079449705219]
 ['M3' 0.33017997094451296 0.3007441750450529 0.30192262258677066
  0.35778088375436645 0.3530721178991103]
 ['M4' 0.3260004776414179 0.2958934625443262 0.402563496782361
  0.324837461909746 0.33492479815826415]
 ['M5' 0.3928723704909395 0.42686270006394605 0.22644196694007804
  0.4765304276128821 0.45128114237898376]
 ['M6' 0.36779541067236887 0.3735048625559528 0.40885355141958535
  0.3945549360460358 0.3979066725529656]
 ['M7' 0.27584655800427665 0.21343135003197303 0.33337289577289264
  0.3746356577213816 0.36908445884691576]
 ['M8' 0.3886928771878444 0.41716127506249273 0.21386185766562923
  0.28346665308161795 0.28155032833224597]]


In [116]:
data

array([['M1', 0.3510774374599885, 0.3444005875515928, 0.4214336606940341,
        0.3225390836415167, 0.3359922875547845],
       ['M2', 0.3803338905816542, 0.4026091375603127, 0.4403038246057073,
        0.2428619703428997, 0.2698079449705219],
       ['M3', 0.33017997094451296, 0.3007441750450529,
        0.30192262258677066, 0.35778088375436645, 0.3530721178991103],
       ['M4', 0.3260004776414179, 0.2958934625443262, 0.402563496782361,
        0.324837461909746, 0.33492479815826415],
       ['M5', 0.3928723704909395, 0.42686270006394605,
        0.22644196694007804, 0.4765304276128821, 0.45128114237898376],
       ['M6', 0.36779541067236887, 0.3735048625559528,
        0.40885355141958535, 0.3945549360460358, 0.3979066725529656],
       ['M7', 0.27584655800427665, 0.21343135003197303,
        0.33337289577289264, 0.3746356577213816, 0.36908445884691576],
       ['M8', 0.3886928771878444, 0.41716127506249273,
        0.21386185766562923, 0.28346665308161795, 0.28155032833224597]],


In [117]:
data=data[:,1:]

In [118]:
data = data.astype(float)

In [119]:
weights=np.array([2,2,3,3,4])
weights

array([2, 2, 3, 3, 4])

In [120]:
impact = ['-', '+', '-', '+', '-']
impact

['-', '+', '-', '+', '-']

In [121]:
data=data*weights*np.where(np.array(impact) == '+', 1, -1)
data

array([[-0.70215487,  0.68880118, -1.26430098,  0.96761725, -1.34396915],
       [-0.76066778,  0.80521828, -1.32091147,  0.72858591, -1.07923178],
       [-0.66035994,  0.60148835, -0.90576787,  1.07334265, -1.41228847],
       [-0.65200096,  0.59178693, -1.20769049,  0.97451239, -1.33969919],
       [-0.78574474,  0.8537254 , -0.6793259 ,  1.42959128, -1.80512457],
       [-0.73559082,  0.74700973, -1.22656065,  1.18366481, -1.59162669],
       [-0.55169312,  0.4268627 , -1.00011869,  1.12390697, -1.47633784],
       [-0.77738575,  0.83432255, -0.64158557,  0.85039996, -1.12620131]])

In [122]:
ideal_sol = np.max(data, axis=0)
negative_ideal_sol = np.min(data, axis=0)
ideal_sol

array([-0.55169312,  0.8537254 , -0.64158557,  1.42959128, -1.07923178])

In [123]:
negative_ideal_sol

array([-0.78574474,  0.4268627 , -1.32091147,  0.72858591, -1.80512457])

In [124]:
distance_to_ideal = np.linalg.norm(data - ideal_sol, axis=1)
distance_to_negative_ideal = np.linalg.norm(data - negative_ideal_sol, axis=1)

In [125]:
topsis_score = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

In [126]:
topsis_score

array([0.41012861, 0.45037082, 0.53117722, 0.41347825, 0.57702762,
       0.41804256, 0.46429246, 0.62744873])

In [127]:
def rank_rows(data, column_index, ascending=True):
    column_values = data[:, column_index]
    sorted_indices = np.argsort(column_values, kind='quicksort')  # Use quicksort for stable sorting

    if not ascending:
        sorted_indices = sorted_indices[::-1]

    ranks = np.empty_like(sorted_indices)
    ranks[sorted_indices] = np.arange(len(sorted_indices)) + 1

    return ranks

column_index_to_rank = 4 
ascending_order = True  

row_ranks = rank_rows(data, column_index_to_rank, ascending_order)
print("Row Ranks based on column {}: {}".format(column_index_to_rank, row_ranks))


Row Ranks based on column 4: [5 8 4 6 1 2 3 7]


In [128]:
df = pd.DataFrame(data2)
df['Rank'] = row_ranks

print(df)

    0         1         2         3         4         5  Rank
0  M1  0.351077  0.344401  0.421434  0.322539  0.335992     5
1  M2  0.380334  0.402609  0.440304  0.242862  0.269808     8
2  M3   0.33018  0.300744  0.301923  0.357781  0.353072     4
3  M4     0.326  0.295893  0.402563  0.324837  0.334925     6
4  M5  0.392872  0.426863  0.226442   0.47653  0.451281     1
5  M6  0.367795  0.373505  0.408854  0.394555  0.397907     2
6  M7  0.275847  0.213431  0.333373  0.374636  0.369084     3
7  M8  0.388693  0.417161  0.213862  0.283467   0.28155     7


In [129]:
excel_file_path = '/Users/krishuppal/Desktop/102103058-result-2.xlsx'
df.to_excel(excel_file_path, index=False)